- name: "create configlets on CVP {{ inventory_hostname }}."
  tags: [provision, apply]
  arista.cvp.cv_configlet_v3:
    configlets: "{{ CVP_VARS.CVP_CONFIGLETS }}"

- name: "Execute pending tasks on {{ inventory_hostname }}"
  tags: [apply]
  arista.cvp.cv_task_v3:
    tasks: "{{ CVP_DEVICES_RESULTS.tasks }}"
  when:
    - execute_tasks|bool
