---
- name: Create required output directories if not present
  tags: [build, provision]
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ documentation_dir }}"
    - "{{ eos_config_dir }}"
    - "{{ devices_dir }}"
  delegate_to: localhost
  run_once: true

- name: Check if structure configuration file exists
  tags: [build, provision]
  stat:
    path: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
  register: stat_result
  delegate_to: localhost
  when: structured_config is not defined

- name: Include device intended structure configuration variables
  tags: [build, provision]
  include_vars: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
  delegate_to: localhost
  when: structured_config is not defined and stat_result.stat.exists

- name: Generate eos intended configuration
  tags: [build, provision]
  template:
    src: eos-intended-config.j2
    dest: "{{ eos_config_dir }}/{{ inventory_hostname }}.cfg"
    mode: 0664
  delegate_to: localhost
  register: eosconfig

- name: Generate device documentation
  tags: [build, provision, documentation]
  delegate_to: localhost
  when: generate_device_documentation | arista.avd.default(true)
  copy:
    content: "{{ lookup('template','eos-device-documentation.j2') | arista.avd.add_md_toc(skip_lines=3) }}"
    dest: "{{ devices_dir }}/{{ inventory_hostname }}.md"
    mode: 0664
