---
# tasks file for dhcp_provisioner

- name: Create required output directories if not present
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ eos_config_dir }}"
    - "{{ structured_cvp_dir }}"
  delegate_to: localhost
  run_once: true

- name: Build DHCP intended variables
  template:
    src: ztp_configuration.j2
    dest: "{{ structured_cvp_dir }}/ztp_configuration.yml"
    mode: 0664
  delegate_to: localhost
  run_once: true

- name: include DHCP variables to build dhcpd.conf file
  include_vars: "{{ structured_cvp_dir }}/ztp_configuration.yml"
  run_once: true

- name: start creation/update process.
  tags: [provision]
  include_tasks: "./{{ ztp_mode }}.yml"
