---
- name: "Generate intented variables"
  tags: [always]
  arista.avd.inventory_to_container:
    inventory: "{{ inventory_file }}"
    container_root: "{{ container_root }}"
    configlet_dir: "{{ eos_config_dir }}"
    configlet_prefix: "{{ configlets_prefix }}"
    destination: "{{ structured_cvp_dir }}/{{ inventory_hostname }}_configlets.yml"
    device_filter: "{{ device_filter }}"
  register: CVP_VARS

- name: "Build DEVICES and CONTAINER definition for {{ inventory_hostname }}"
  tags: [generate, build, provision]
  template:
    src: "cvp-devices-v3.j2"
    dest: "{{ structured_cvp_dir }}/{{ inventory_hostname }}.yml"
    mode: 0664
  delegate_to: localhost
  run_once: true

#################################################

# If state=present launch creation/update process
# If state=absent launch deletion process
- name: Start creation/update process.
  tags: [provision, online]
  include_tasks: "{{ cv_collection }}/{{ state }}.yml"

#################################################
