---
- name: generate intented variables
  tags: [always]
  arista.avd.inventory_to_container:
    inventory: "{{ inventory_file }}"
    container_root: "{{ container_root }}"
    configlet_dir: "{{ eos_config_dir }}"
    configlet_prefix: "{{ configlets_prefix }}"
    destination: "{{ structured_cvp_dir }}/{{ inventory_hostname }}_configlets.yml"
    device_filter: "{{ device_filter }}"
  register: CVP_VARS
