---
# tasks file for build_directories

- name: "Cleanup existing folders in {{ output_dir }}"
  file:
    path: "{{ output_dir }}"
    state: absent
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ output_dir }}"
  file:
    path: "{{ output_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ structured_dir_name }} for structured YAML files"
  file:
    path: "{{ structured_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ eos_config_dir_name }} for EOS Configuration files"
  file:
    path: "{{ eos_config_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ structured_cvp_dir_name }} for CVP structured YAML files"
  file:
    path: "{{ structured_cvp_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create documentation folder: {{ documentation_dir_name }}"
  file:
    path: "{{ documentation_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ fabric_dir_name }} for Fabric documentation"
  file:
    path: "{{ fabric_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ devices_dir_name }} for EOS documentation"
  file:
    path: "{{ devices_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ post_running_config_backup_dir }} for EOS post backup dir"
  file:
    path: "{{ post_running_config_backup_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ pre_running_config_backup_dir }} for EOS pre backup dir"
  file:
    path: "{{ pre_running_config_backup_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: "Create folder {{ eos_validate_state_name }} for EOS state report dir"
  file:
    path: "{{ eos_validate_state_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True

- name: Create output directory for each EOS device
  file:
    path: "{{ snapshots_backup_dir }}"
    state: directory
    mode: 0775
  delegate_to: localhost
  run_once: True
